# Generated by Django 3.2.5 on 2021-07-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdf')),
                ('video', models.FileField(upload_to='videos')),
                ('Session_name', models.CharField(max_length=25)),
            ],
        ),
    ]
