# Generated by Django 3.2.5 on 2021-07-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ask_Q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ask',
        ),
    ]
