# Generated by Django 3.2.5 on 2021-07-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210725_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ass_name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('deadline', models.DateField()),
                ('pdf', models.FileField(upload_to='pdf_ass')),
                ('url_form', models.CharField(max_length=75)),
            ],
        ),
        migrations.DeleteModel(
            name='ask_Q',
        ),
        migrations.DeleteModel(
            name='assignment_stu',
        ),
        migrations.DeleteModel(
            name='upload_as',
        ),
    ]
