# Generated by Django 3.2.5 on 2021-07-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210731_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='url_form',
            field=models.URLField(),
        ),
    ]
